version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: postgres-streamingdb
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: usuario
      POSTGRES_PASSWORD: senha
      POSTGRES_DB: streamingdb
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - streaming-network
    restart: unless-stopped

  redis:
    image: redis:alpine
    container_name: redis-streaming
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - streaming-network
    restart: unless-stopped

volumes:
  postgres_data:
  redis_data:

networks:
  streaming-network:
    driver: bridge 